import "./globals.css"
//estilos
import Link from "next/link";
import{Commissioner} from"next/font/google"
import Avatar from "@/assets/images/Avatar.png"




const commissioner = Commissioner({subsets:["latin"]});

export const metadata = {
  title:"Create Next App",
  description:"Generated by cretae next App"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${commissioner.className} antialiased`}>
      <main className="grid min-h-screen items-center py-20 bg-gray-900">
          <div className="sm:w-[500px] mx-auto rounded-md bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-1  md:w-[700px]">
            <div className="rounded bg-gray-100 p-8">
              <Link href="/">
                <img
                  src={Avatar.src}
                  alt="Imagen avatar de presentación"
                  className="mx-auto -mt-20 mb-8 rounded-full "
                  width={225}
                  height={225}
                />
              </Link>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}